[package]
name = "rigel-server-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.52.3", features = ["full"] }
dotenvy = "0.15.7"
axum = { version = "0.8.9", features = ["multipart", "ws"] }
tower-http = { version = "0.6.11", features = ["cors", "fs"] }
futures-util = "0.3.32"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
chrono = { version = "0.4.38", features = ["serde"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "mysql", "macros", "chrono"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.23.1", features = ["v4"] }
bitflags = "2.11.1"
base64 = "0.22.1"
bcrypt = "0.19.1"
hmac = "0.13.0"
sha2 = "0.11.0"
zstd = "0.13.3"
