CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(20) NOT NULL PRIMARY KEY,
    created_at BIGINT UNSIGNED NOT NULL,
    bot TINYINT NOT NULL DEFAULT 0,
    public_flags INT UNSIGNED NOT NULL DEFAULT 0,
    username VARCHAR(32) NOT NULL,
    password_hash VARCHAR(255) DEFAULT NULL,
    global_name VARCHAR(32) DEFAULT NULL,
    discriminator VARCHAR(4) NOT NULL DEFAULT "0",
    avatar VARCHAR(255) DEFAULT NULL,
    banner VARCHAR(255) DEFAULT NULL
);